# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-chipseq-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  ## conda-forge packages
  - openjdk=11.0.1      # Needed for FastQC - conda build hangs without this
  - gawk=4.2.1
  - r-markdown=0.9
  - r-catools=1.17.1.2
  - r-snow=0.4_3
  - r-r.utils=2.8.0
  - r-stringr=1.4.0
  - r-evaluate=0.13
  - r-domc=1.3.5
  - r-ggplot2=3.1.0
  - r-knitr=1.21
  - r-rmysql=0.10.13
  - r-doparallel=1.0.14

  ## bioconda packages
  - fastqc=0.11.8
  - trim-galore=0.5.0
  - bwa=0.7.17
  - bedtools=2.27.1
  - samtools=1.9
  - picard=2.18.27
  - deeptools=3.2.0
  - macs2=2.1.2
  - multiqc=1.7

  - r-spp=1.15.5
  - bioconductor-rsamtools=1.34.0
  - bioconductor-shortread=1.40.0
  - bioconductor-genomicranges=1.34.0
  - bioconductor-genomicfeatures=1.34.1
  - bioconductor-ensembldb=2.6.3
  - bioconductor-chippeakanno=3.16.0
  - bioconductor-biomart=2.38.0
  - bioconductor-rtracklayer=1.42.1
  - bioconductor-bsgenome=1.50.0
  - bioconductor-bsgenome.hsapiens.ucsc.hg19=1.4.0
  - bioconductor-bsgenome.mmusculus.ucsc.mm10=1.4.0
  - bioconductor-org.hs.eg.db=3.7.0
  - bioconductor-org.mm.eg.db=3.7.0
